### PR TITLE
Handle images with no user properly

### LINKED ISSUE #121: v2 doesn't show image details
## Expected behavior
- Click on a image name
- See image details (image id, author, etc)
## Actual behavior

After clicking on any image the details page load empty. This is happening because "/10" is always being appended to the repository details url:

https://registry-ui.xxxxx.com/v2/busybox/10/tags/list

it should be:

https://registry-ui.xxxxx.com/v2/busybox/tags/list
## Steps to reproduce the problem
- Run container
- Click on an image name
- See the empty details and the browser url includes "/10" (page 10 ?)
## Specifications
- [x] Which version of docker (`docker version`) are you running? 1.10.3
- [x] Which operating system do you use? ubuntu 16.04 beta2
- [x] Which version of the docker-registry-frontend are you running? v2 container, pulled on 04-16/17-2016
  - If you have the frontend running already you can find the version at the very bottom on every page.

git version: d5dd87d

### PR DESCRIPTION
**Pull request by msabramo**
This makes it so that images that don't have a user (e.g.: `ubuntu` rather than `gliderlabs/registrator`) work properly.

There have been several PRs I think that tried to tackle this (e.g.:  #100 , #104 & #97), but this one has tests (see https://github.com/kwk/docker-registry-frontend/pull/147/commits/9cb8ea158810371b057f43e324eb59536cd50456)! 😄 

Note that this changes the routing in a fairly significant way, because it switches to using query string variables for things like `tagsPerPage` and `tagPage`. The reason is that this helps to make the routes less ambiguous. For example, with the old routing, if you had a URI like `/repository/ubuntu/10` (the intent is that this means no user, image name is `ubuntu`, 10 tags per page), the routing could easily get confused and match a route like `/repository/:repositoryUser/:repositoryName`  and think that `repositoryUser` is `ubuntu` and `repositoryName` is `10`. Switching to query string variables removes this ambiguity, because `?tagsPerPage=10` makes it clear that the `10` is the number of tags per page and not the repository name.

Fixes #121 
Closes #97, #100, #104

### CODE REVIEW

File: app/repository/repository-detail-controller.js [hunk 1]
```diff
@@ -27,13 +34,13 @@ angular.module('repository-detail-controller', ['registry-services', 'app-mode-s
     $scope.getNextHref = function (){
       if($scope.maxTagsPage > $scope.tagsCurrentPage){
         var nextPageNumber = $scope.tagsCurrentPage + 1;
-        return '/repository/'+$scope.repository+'/'+ $scope.tagsPerPage +'/' +nextPageNumber;
+        return '/repository/'+$scope.repository+'?tagsPerPage='+ $scope.tagsPerPage +'&tagPage=' +nextPageNumber;
```
Comment (kwk) [inline app/repository/repository-detail-controller.js:37]: I'm not sure that `tagsPerPage` can be a parameter. In line 63 of `app/app.js` this route is defined as 

``` javascript
when('/repository/:repositoryUser/:repositoryName/:tagsPerPage?/:tagPage?', {
```

As you can see, here it is part of the path and not a parameter.

Correct me, if I'm mistaken.

File: app/repository/repository-detail-controller.js [hunk 2]
```diff
@@ -27,13 +34,13 @@ angular.module('repository-detail-controller', ['registry-services', 'app-mode-s
...
       }
       return '#'
-    } 
+    }
     $scope.getFirstHref = function (){
       if($scope.tagsCurrentPage > 1){
-        return '/repository/'+$scope.repository+'/' + $scope.tagsPerPage +'/1';
+        return '/repository/'+$scope.repository+'?tagsPerPage=' + $scope.tagsPerPage;
```
Comment (kwk) [inline app/repository/repository-detail-controller.js:43]: Same here.

File: app/repository/repository-detail.html [hunk 3]
```diff
@@ -40,14 +39,14 @@
           <span class="caret"></span>
         </a>
         <ul class="dropdown-menu">
-          <li><a href="repository/{{repository}}">Show all</a></li>
+          <li><a href="repository/{{repository}}?tagsPerPage=all">Show all</a></li>
```
Comment (kwk) [inline app/repository/repository-detail.html:42]: Can `tagsPerPage` really be a parameter here and for the next few lines?

File: app/repository/repository-detail-controller.js (hunk 1 above)
Comment (msabramo) [inline app/repository/repository-detail-controller.js:37]: From https://www.sitepoint.com/premium/books/angularjs-novice-to-ninja/preview/using-routeparams-in-the-controller-6e0d5e2:

> Apart from named parameters, `$routeParams` also parses the query string, if present. So, if your URL contains a query string like `?key1=value1`, the key/value pair is added to `$routeParams`.

Also see the example at the bottom of https://docs.angularjs.org/api/ngRoute/service/$routeParams:

``` javascript
// Given:
// URL: http://server.com/index.html#/Chapter/1/Section/2?search=moby
// Route: /Chapter/:chapterId/Section/:sectionId
//
// Then
$routeParams ==> {chapterId:'1', sectionId:'2', search:'moby'}
```

Also I think you'll find it works if you checkout my branch and run it. Especially if you use Chrome and install the [ng-inspector for AngularJS Chrome extension](https://chrome.google.com/webstore/detail/ng-inspector-for-angularj/aadgmnobpdmgmigaicncghmmoeflnamj); with that extension installed, you can go to any page rendered by Angular and click the little "A" button in the toolbar and get a pane that allows you to browse the values of all the variables in `$scope`.

screen shot 2016-07-20 at 7 08 23 am

I did forget to remove `:tagsPerPage?` from the routes though. I can update that.

Comment (msabramo) [inline app/repository/repository-detail-controller.js:37]: OK, I:
- removed `:tagsPerPage` from the repository detail routes in 8e635d2421e0c089d7c20bc7c0c881412814c0ba.
- updated the unit tests to pass `tagsPerPage` as a query string parameter rather than in the route in 15d5cdb.

File: app/repository/repository-detail-controller.js (hunk 2 above)
Comment (msabramo) [inline app/repository/repository-detail-controller.js:43]: Yeah, see https://github.com/kwk/docker-registry-frontend/pull/147#discussion_r71525785

File: app/repository/repository-detail.html (hunk 3 above)
Comment (msabramo) [inline app/repository/repository-detail.html:42]: Yeah, see https://github.com/kwk/docker-registry-frontend/pull/147#discussion_r71525785

File: app/repository/repository-detail-controller.js (hunk 1 above)
Comment (msabramo) [inline app/repository/repository-detail-controller.js:37]: @kwk: Have I convinced you that `tagsPerPage` can be a query string parameter? If so, I think it also makes sense to do the same with `reposPerPage`...

**Comment by msabramo** [comment]
@kwk: How does this look?

**Comment by msabramo** [comment]
Awesome!
